// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Replay.Data;

#nullable disable

namespace Replay.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240723124110_MergePinstance")]
    partial class MergePinstance
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.31");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProcessBlueprintRoles", b =>
                {
                    b.Property<int>("PermittedRolesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessBlueprintsProcessBlueprintName")
                        .HasColumnType("TEXT");

                    b.HasKey("PermittedRolesId", "ProcessBlueprintsProcessBlueprintName");

                    b.HasIndex("ProcessBlueprintsProcessBlueprintName");

                    b.ToTable("ProcessBlueprintRoles");
                });

            modelBuilder.Entity("Replay.Model.ContractType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContractType");
                });

            modelBuilder.Entity("Replay.Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Replay.Model.ProcessBlueprint", b =>
                {
                    b.Property<string>("ProcessBlueprintName")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("ProcessBlueprintName");

                    b.ToTable("ProcessBlueprint");
                });

            modelBuilder.Entity("Replay.Model.ProcessInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessInstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceUserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsibleUserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ReferenceUserEmail");

                    b.HasIndex("ResponsibleUserEmail");

                    b.ToTable("ProcessInstance");
                });

            modelBuilder.Entity("Replay.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Replay.Model.TaskInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedUserEmail")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysRelToProcessInstance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isAsap")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedRoleId");

                    b.HasIndex("AssignedUserEmail");

                    b.HasIndex("ProcessInstanceId");

                    b.ToTable("TaskInstance");
                });

            modelBuilder.Entity("Replay.Model.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TaskBlueprint", b =>
                {
                    b.Property<string>("TaskName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysRelativeToDueDate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DueDateType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<int>("PermittedRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessBlueprintName")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskName");

                    b.HasIndex("PermittedRoleId");

                    b.HasIndex("ProcessBlueprintName");

                    b.ToTable("TaskBlueprint");
                });

            modelBuilder.Entity("TaskBlueprintContractTypes", b =>
                {
                    b.Property<int>("PermittedContractTypesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TasksTaskName")
                        .HasColumnType("TEXT");

                    b.HasKey("PermittedContractTypesId", "TasksTaskName");

                    b.HasIndex("TasksTaskName");

                    b.ToTable("TaskBlueprintContractTypes");
                });

            modelBuilder.Entity("TaskBlueprintDepartments", b =>
                {
                    b.Property<int>("PermittedDepartmentsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TasksTaskName")
                        .HasColumnType("TEXT");

                    b.HasKey("PermittedDepartmentsId", "TasksTaskName");

                    b.HasIndex("TasksTaskName");

                    b.ToTable("TaskBlueprintDepartments");
                });

            modelBuilder.Entity("UserDepartments", b =>
                {
                    b.Property<int>("DepartmentsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsersEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentsId", "UsersEmail");

                    b.HasIndex("UsersEmail");

                    b.ToTable("UserDepartments");
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsersEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("RolesId", "UsersEmail");

                    b.HasIndex("UsersEmail");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProcessBlueprintRoles", b =>
                {
                    b.HasOne("Replay.Model.Role", null)
                        .WithMany()
                        .HasForeignKey("PermittedRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Replay.Model.ProcessBlueprint", null)
                        .WithMany()
                        .HasForeignKey("ProcessBlueprintsProcessBlueprintName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Replay.Model.ProcessInstance", b =>
                {
                    b.HasOne("Replay.Model.ContractType", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Replay.Model.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Replay.Model.User", "ReferenceUser")
                        .WithMany()
                        .HasForeignKey("ReferenceUserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Replay.Model.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Department");

                    b.Navigation("ReferenceUser");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("Replay.Model.TaskInstance", b =>
                {
                    b.HasOne("Replay.Model.Role", "AssignedRole")
                        .WithMany()
                        .HasForeignKey("AssignedRoleId");

                    b.HasOne("Replay.Model.User", "AssignedUser")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedUserEmail");

                    b.HasOne("Replay.Model.ProcessInstance", "ProcessInstance")
                        .WithMany("AllTasks")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedRole");

                    b.Navigation("AssignedUser");

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("TaskBlueprint", b =>
                {
                    b.HasOne("Replay.Model.Role", "PermittedRole")
                        .WithMany("Tasks")
                        .HasForeignKey("PermittedRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Replay.Model.ProcessBlueprint", "ProcessBlueprint")
                        .WithMany("Tasks")
                        .HasForeignKey("ProcessBlueprintName")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PermittedRole");

                    b.Navigation("ProcessBlueprint");
                });

            modelBuilder.Entity("TaskBlueprintContractTypes", b =>
                {
                    b.HasOne("Replay.Model.ContractType", null)
                        .WithMany()
                        .HasForeignKey("PermittedContractTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskBlueprint", null)
                        .WithMany()
                        .HasForeignKey("TasksTaskName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskBlueprintDepartments", b =>
                {
                    b.HasOne("Replay.Model.Department", null)
                        .WithMany()
                        .HasForeignKey("PermittedDepartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskBlueprint", null)
                        .WithMany()
                        .HasForeignKey("TasksTaskName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserDepartments", b =>
                {
                    b.HasOne("Replay.Model.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Replay.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UsersEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("Replay.Model.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Replay.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UsersEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Replay.Model.ProcessBlueprint", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Replay.Model.ProcessInstance", b =>
                {
                    b.Navigation("AllTasks");
                });

            modelBuilder.Entity("Replay.Model.Role", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Replay.Model.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
